-- apply changes
create table users (
  id                            bigint generated by default as identity not null,
  first_name                    varchar(255),
  last_name                     varchar(255),
  email                         varchar(255),
  password                      varchar(255),
  constraint pk_users primary key (id)
);

